#version 450
#extension GL_GOOGLE_include_directive : require

#include "btrlib/ConvertDimension.glsl"
#include "btrlib/Common.glsl"
#include "btrlib/Math.glsl"

#define USE_GI2D 0
#define USE_PM 0
#include "GI2D.glsl"

layout (local_size_x = 32, local_size_y = 32) in;

shared uint s_bit[16][2];
shared uint s_light_bit[16][2];
void main()
{
//	uvec2 gi = gl_GlobalInvocationID.xy >> 1;
//	uint tiled_1D_index = gi.x + gi.y * (u_gi2d_info.m_resolution.x>>1);
//	b_fragment_map4[store] = bit;
}

