#version 460

#extension GL_GOOGLE_include_directive : require
#define USE_Flowmap 0
#include "Flowmap.glsl"

layout (local_size_x=8, local_size_y=8) in;

void main()
{
	ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
	uint index = uv.x + uv.y*u_info.reso.x;
	float v = b_diffusion[index];
//	if(abs(v) >= 1.)
//	{
//		v = v-sign(v)*log(abs(v));
		v = v*0.95;
//	}
	b_diffusion[index] = v;

//	float diffuse = b_diffusion[index];
//	v += diffuse;
//	b_value[index] = v;
//	b_diffusion[index]= 0.;
}
