#version 460
#extension GL_GOOGLE_include_directive : require

#include "Sky.glsl"

layout (local_size_x = 32, local_size_y = 32) in;
layout(push_constant) uniform Input
{
	vec3 window;
} constant;

void main()
{
	uvec3 reso = gl_NumWorkGroups * gl_WorkGroupSize;
	vec2 uv = ((vec2(gl_GlobalInvocationID.xy)+0.5) / reso.xy);
	vec4 c = texture(s_render_map, uv);
	imageStore(i_render_target, ivec2(gl_GlobalInvocationID.xy), c);
}