#version 460
#extension GL_GOOGLE_include_directive : require

#include "Sky.glsl"
layout (local_size_x = 32, local_size_y = 32) in;

void main()
{
	float y = mod(constant.window.x*0.1, 1.);
	vec2 uv = vec2(gl_GlobalInvocationID.xy+0.5) / vec2(gl_NumWorkGroups.xy*gl_WorkGroupSize.xy);
	vec4 v = texture(s_along_density_map, vec3(uv.x, y, uv.y)); 
	imageStore(i_render_target, ivec2(gl_GlobalInvocationID.xy), vec4(v.xxx, 1.));

}