#version 460
#extension GL_GOOGLE_include_directive : require

#define USE_WORLEYNOISE 0
#include "WorleyNoise.glsl"

layout (local_size_x = 32, local_size_y = 32) in;


void main()
{

	vec4 v = vec4(0.);
	v[0] = value_noise(gl_GlobalInvocationID.xyz+23, 5);
	v[1] = 0.2;
	v[2] = 1.;
	v = clamp(v, vec4(0.), vec4(1.));
	imageStore(i_weather_map, ivec2(gl_GlobalInvocationID.xy), uvec4(v* vec4(255.)));

}