#define TILED_MAP


#define BRICK_SIZE 32
#define BRICK_TOTAL (BRICK_SIZE*BRICK_SIZE*BRICK_SIZE)
#define BRICK_SCALE1 4
#define BRICK_SUB_SIZE (BRICK_SIZE * BRICK_SCALE1)
#define BRICK_SUB_TOTAL (BRICK_SUB_SIZE*BRICK_SUB_SIZE*BRICK_SUB_SIZE)
#define BRICK_AREA_MIN vec3(-100.f)
#define BRICK_AREA_MAX vec3(100.f)
#define BRICK_CELL_SIZE ((BRICK_AREA_MAX-BRICK_AREA_MIN) / BRICK_SIZE)
#define BRICK_SUB_CELL_SIZE ((BRICK_AREA_MAX-BRICK_AREA_MIN) / BRICK_SUB_SIZE)


// PM3
#define PHOTON_BLOCK_NUM 64
#define TRIANGLE_BLOCK_NUM 4
#define PHOTON_BATCH_BUFFER_SIZE 256
#define PHOTON_EMIT_BUFFER_SIZE (1024 * 1024) 