#version 450
#extension GL_GOOGLE_cpp_style_line_directive : require

#include </Common.glsl>
#define USE_PARTICLE 0
#include </Particle.glsl>

#define USE_SYSTEM 1
#include <applib/System.glsl>

layout (local_size_x = 128, local_size_y = 1) in;

void main()
{
	uint index = gl_GlobalInvocationID.x;
	if(index >= b_emitter_num.x)
	{
		return;
	}

	uint dst_index = atomicAdd(b_draw_cmd.vertexCount, 1);
	b_particle[constant.m_offset + dst_index] = b_particle_emit[index];

}