#version 460
#extension GL_GOOGLE_include_directive : require

#define USE_AppModel 0
#define USE_AppModel_Update 1
#include "applib/AppModel.glsl"


layout (local_size_x = 1024, local_size_y = 1) in;


void main() 
{
	uint index = gl_GlobalInvocationID.x;
	if(index >= b_model_instancing_info.instanceAliveNum){ return; }

	b_playing_animation[index].time += 60. + float(index)*0.01;
//	b_playing_animation[index].time += 0.016 + float(index)*0.00001;
}

