#version 450

#extension GL_GOOGLE_cpp_style_line_directive : require

#define USE_APPMODEL 0
#include <applib/model/MultiModel.glsl>

layout (local_size_x = 1024, local_size_y = 1) in;


void main() 
{
	uint index = gl_GlobalInvocationID.x;
	if(index >= b_model_instancing_info.instanceAliveNum){ return; }

//	AnimationWork anime_work = playingMotion[index];

	b_animation_work[index].time += 60. + float(index)*0.01;
//	playingMotion[index].time += 0.016 + float(index)*0.00001;
}

