#version 450

#extension GL_GOOGLE_cpp_style_line_directive : require

#define USE_UI 0
#define USE_UI_ANIME 1
#include <UI.glsl>

#define USE_SYSTEM 2
#include <applib/System.glsl>

layout (local_size_x = 1024, local_size_y = 1) in;


void main() 
{
	uint index = gl_GlobalInvocationID.x;
//	if(index >= u_model_instancing_info.instanceAliveNum){ return; }

//	PlayingAnimation pm = playingMotion[index];

//	playingMotion[index].time += 0.016 + float(index)*0.00001;
}

