#version 460
#extension GL_GOOGLE_include_directive : require

#define USE_PM 0
#include "PM.glsl"
layout (local_size_x = 64, local_size_y = 16, local_size_z = 1) in;
/*
layout(std140, binding=0) uniform BrickParamUniform {
	BrickParam uParam;
};

layout(std430, binding=0) writeonly restrict buffer LLHeadBuffer {
	uint bLLHead[];
};
*/

void main() 
{
//	ivec3 index = ivec3(gl_GlobalInvocationID.xyz);
//	int i = convert3DTo1D(index, uParam.num1);
//	bLLHead[i] = 0xFFFFFFFF;
}