#version 460
#extension GL_GOOGLE_include_directive : require

#define USE_Rigidbody2D 0
#define USE_GI2D 1
#define USE_MakeRigidbody 2
#include "GI2D.glsl"
#include "Rigidbody2D.glsl"

layout (local_size_x = RB_PARTICLE_BLOCK_SIZE) in;

void main()
{
	dvec2 cm = dvec2(b_make_rigidbody.cm_work) / CM_WORK_PRECISION / b_make_rigidbody.pnum;
	b_make_rigidbody.cm = vec2(cm);
	b_make_rigidbody.cm_work = i64vec2(0);

}