#version 460
#extension GL_GOOGLE_include_directive : require

#define USE_Rigidbody2D 0
#define USE_GI2D 1
#define USE_MakeRigidbody 2
#include "GI2D.glsl"
#include "Rigidbody2D.glsl"

layout (local_size_x = １) in;

layout(push_constant) uniform Input
{
	uint particle_block_num;
	int p;
	uvec2 reso;
} constant;

void main()
{
	b_make_param.pb_num = uvec4((b_make_rigidbody.pnum+(RB_PARTICLE_BLOCK_SIZE-1)) / RB_PARTICLE_BLOCK_SIZE,1,1, b_make_rigidbody.pnum);
	pow2size_minmax
}