#version 460
#extension GL_GOOGLE_include_directive : require

#define USE_Rigidbody2D 0
#define USE_GI2D 1
#include "GI2D.glsl"
#include "Rigidbody2D.glsl"

layout (local_size_x = 1) in;

void main() 
{
	uint rbid = gl_GlobalInvocationID.x;
	if(rbid >= b_world.rigidbody_num){ return; }

	vec2 cm = b_rigidbody[rbid].cm_work / 65535.;
	b_rigidbody[rbid].cm = cm;

	b_rigidbody[rbid].cm_work = ivec2(0);

}