#version 460

#extension GL_GOOGLE_include_directive : require
#define USE_Voxel 0
#include "Voxel.glsl"

layout (local_size_x = 64) in;

void main() 
{
	int top_index = int(gl_GlobalInvocationID.x);
	if(top_index >= b_interior_counter[1].w) { return; }
	
	top_index += b_interior_counter[0].w;
	uvec2 c = bitCount(b_interior[top_index].bitmask);
	uint count = c.x+c.y;

	int leaf_index = atomicAdd(b_leaf_counter, int(count));

	b_interior[top_index].child = leaf_index;

}
